#!/bin/bash

echo "🔗 Updating Supabase Configuration"
echo "=================================="

# Get project details from user
read -p "Enter your Supabase Project URL (e.g., https://abc123.supabase.co): " SUPABASE_URL
read -p "Enter your Supabase anon key: " SUPABASE_ANON_KEY

# Update the client configuration
cat > src/integrations/supabase/client.ts << EOF
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Production Supabase environment
const SUPABASE_URL = "$SUPABASE_URL";
const SUPABASE_PUBLISHABLE_KEY = "$SUPABASE_ANON_KEY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
EOF

echo "✅ Configuration updated!"
echo "🔄 Restarting development server..."

# Restart the development server
pkill -f "npm run dev" || true
npm run dev &

echo "🎉 Done! Your app is now connected to Supabase cloud."
echo "📱 Test your app at: http://localhost:8080" 